#ifndef ERRORS_H
#define ERRORS_H

typedef int err_t;

#define OK (0)
#define MEMORY_ALLOCATION_ERROR (1)
#define DEREFERENCING_NULL_PTR (2)
#define INDEX_OUT_OF_BOUNDS (3)
#define OPENING_THE_FILE_ERROR (4)
#define INVALID_NUMERIC_BASE (5)
#define INVALID_NUM_TO_CHAR_CONVERSION (6)
#define INVALID_CHAR_TO_NUM_CONVERSION (7)
#define INVALID_FLAG (8)
#define INVALID_STREAM_PTR (9)
#define INVALID_NUMBER (10)
#define INVALID_COMBINATION_SIZE (11)
#define EQUAL_ELEMENTS_FOUND (12)
#define ERROR_READING_FROM_STDIN (13)
#define NO_SUCH_ENTRY_IN_COLLECTION (14)
#define STACK_IS_EMPTY (15)
#define REPEATING_KEY (16)
#define KEY_NOT_FOUND (17)
#define ZERO_MEMORY_ALLOCATION (18)
#define REGEX_FAILED (19)
#define INVALID_INPUT_DATA (20)
#define INVALID_CLI_ARGUMENT (21)
#define ZERO_DIVISION (22)

#endif
