#ifndef ERRORS_H
#define ERRORS_H

#define OK (0)
#define MEMORY_ALLOCATE_ERROR (1)
#define DEREFERENCING_NULL_PTR (2)
#define INDEX_OUT_OF_BOUNDS (3)
#define OPENING_THE_FILE_ERROR (4)
#define INVALID_NUMERIC_BASE (5)
#define INVALID_NUM_TO_CHAR_CONVERSION (6)
#define INVALID_CHAR_TO_NUM_CONVERSION (7)

#endif